### ISSUE TITLE
Specify supported comment formats

### ISSUE THREAD

**Issue by jkup** [tc39/source-map-rfc#54]
Originally from https://github.com/tc39/source-map-rfc/issues/10 worth making a separate issue about comment formats.

> Similarly, the v3 specification indicates that //# is preferred to reference the source-map location from JavaScript, but that the //@ form is also permitted. Is a modern implementation required to support both forms?

**Comment by jkup** [comment]
Is the old format used? If so, do we want to consider dropping support for it. Could Chrome help us find metrics for how often these are used?

**Comment by kamilogorek** [comment]
Sentry should be able to provide some meaningful data around it as well.

We "just" need additional [metric](https://github.com/getsentry/symbolicator/blob/e179bb44435ca803d1e8513f2c68c0fec1d45443/crates/symbolicator-service/src/js/metrics.rs) around https://github.com/getsentry/symbolicator/blob/e179bb44435ca803d1e8513f2c68c0fec1d45443/crates/symbolicator-service/src/services/sourcemap_lookup.rs#L950 (requires a change to https://github.com/getsentry/symbolic/blob/e96f555fc06f0855fed32a2fee767fa1743115f2/symbolic-debuginfo/src/js.rs#L15 as well)

cc @Swatinem @mitsuhiko

**Comment by Swatinem** [comment]
I’m afraid its not quite that easy. There is different places, also in sentry-cli which read that reference and put it in a more discoverable place. Also changes to symbolic to expose any kind of metric would require a breaking release as well :-(

**Comment by jkup** [comment]
@Swatinem no problem at all! @szuend, do you know how feasible / easy it would be to pull some metrics from Chrome around how often these old style comments are used in source maps? Specifically, this is discussing how we move forward with this part of the spec https://github.com/tc39/source-map-spec/blob/main/source-map-rev3.md#linking-generated-code-to-source-maps

**Comment by szuend** [comment]
The metric does not exist yet but I'm planning to add a new metric to V8 that reports one of four values for each parsed script: No source map, HTTP header, //# or //@. We need some buy-in from V8 folks though as we need to record a bit in the lexer.

It'll also take some time for the metric to cycle into Chrome Stable afterwards.

**Comment by szuend** [comment]
Short update: Unfortunately adding detailed metrics as I initially planned is a bit tricky due to the current V8 architecture. I opted for a simple use counter instead how often we see the "@" sign at script parse time. Chromestatus.com can then relate this to page loads: "What percentage of page loads see the "@" sign when parsing scripts?" Based on this we can decide if more detailed metrics are required.

The metric is here: https://chromestatus.com/metrics/feature/timeline/popularity/4676

The metric landed with Chrome 120 so the current numbers are from the Canary/Dev channel. Chrome 120 will be promoted to beta on Nov 1st and stable at the end of November, so keep that in mind when looking at the numbers.

At the moment it looks like ~0.06% of page loads feature the scripts with "//@" magic comment.

**Comment by jkup** [comment]
Thank you for researching it! Looks like we're good to merge https://github.com/tc39/source-map-spec/pull/23 now since that's a fair amount of users.
